version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  #-cd src
  # Display .NET Core version
  - cmd: dotnet --version
  # Display normal restore text
  - dotnet restore
  # Display minimal restore text
  #-dotnet restore --verbosity m
build_script:
  - cmd: dotnet build
deploy: off